### PR TITLE
Add PHP 7.2. and 7.3 to Travis, fix __sleep() being defined as static

### PR DESCRIPTION
**Pull request by maksimovic**
Build with HHVM is failing because Travis tries `composer self-update` and it fails badly:
https://travis-ci.org/maksimovic/enumerable-type/jobs/494774587

I've ommited the self-update from the travis.yml but Travis is doing it on its own anyway. Will look for a workaround later.

### CODE REVIEW

**Comment by antanas-arvasevicius** [comment]
Thanks for pull request.  I'm curious why you've removed static from __sleep? Is there are changes to serialization logic in php 7.2/7.3? 
As I'd remembered, I've added static to __sleep to hide __sleep method from public API, when inspecting php sources I found out that statics is also evaluated during serialization.

**Comment by maksimovic** [comment]
Making it static won't really hide the method from the public API; child classes will still be able to "see" it, as well as user's IDE will happily offer to autocomplete `ChildClass::__sleep()` - and PHP will run it without complains.

Also, inspection tools will complain about converting the method to static (although the method continues to work), so that's why I just made it non-static and kept the exception being thrown.

If you wan't to really disable serializing and hide the methods, why not just make `__sleep()` and `__wakeup()` private?

I've put a quick demo here: https://3v4l.org/OT6YI

**Comment by maksimovic** [comment]
Re HHVM: Looks like its a no-go:
https://github.com/composer/composer/issues/7990
https://github.com/composer/composer/commit/d9f873d00e6670f6802441e21538e0e4704128a2

**Comment by antanas-arvasevicius** [comment]
> If you wan't to really disable serializing and hide the methods, why not just make `__sleep()` and `__wakeup()` private?

As I remember, private __sleep() was done at first, but wanted some more nicer error message instead of  ```Warning: Invalid callback A::__sleep, cannot access private method A::__sleep()```

Yes removing static from __sleep is good point to keep code analyzers quiet :-)

PS. I'm curious how HHVM users will now manage dependencies if composer is not supported anymore...

**Comment by maksimovic** [comment]
> As I remember, private __sleep() was done at first, but wanted some more nicer error message instead of `Warning: Invalid callback A::__sleep, cannot access private method A::__sleep()`

Well, it can stay that way, I don't mind :)

> PS. I'm curious how HHVM users will now manage dependencies if composer is not supported anymore...

HHVM [officially announced ending PHP support](https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html), so I guess that current users will have to stay away from HHVM 4 and stay on 3.30

P.S. Out of a temporary boredom I've set the default distro for Travis to be Xenial, and a fallback to Trusty for 5.4 and 5.5 tests, [works fine](https://travis-ci.org/maksimovic/enumerable-type/builds/494919980). No special reason... if you want I can revert that commit.

**Comment by antanas-arvasevicius** [comment]
thanks for updates

**Pull request merged**
